export const data = [
    {
        id: 1,
        imageuurl: '/images/Jasset1.jpeg',
        heading: 'Work From (CPH) The World: Tannaz Torabi',
        para1: 'Mason Studio | Work From The World with Tannaz Torabi, Project Designer',
        Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '


    },

    {
        id: 2,
        imageuurl: '/images/Jasset2.jpeg',
        heading: 'Refuge inthe water',
        para1: 'Refuge In The Water brings the outdoors in and offers a pause with nature. ',
        Location: 'World Health Organization (WHO) estimates  ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset3.jpeg',
        heading: 'Mason Minute with Marwa Istanbuli',
        para1: 'Marwa Istanbuli is a Montreal-based project designer inspired by textural complexity within spaces and shares her story in this timestamp for Mason Minute.  While exploring unconventional ways of layering materiality, to creating meaningful, unique experiences for everyday users while challenging the status quo, she brings her vision, intuition and drive to the world of design.',
        // Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset4.jpeg',
        heading: 'Mason Studio featured in Office Snapshots',
        para1: 'Mason Studio is a place to learn, connect and reflect. Summertime is always ideal for immersing yourself in the pages of a good book – whether revisiting a childhood classic or unravelling design methodology, our book exchange is a place for discovery and discourse. It’s an integral part of cultivating a culture of experimentation, and a gathering space to work during our weekly collaboration days. ⁠',
        // Location: ' ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset5.jpeg',
        heading: 'IDC Summer Mixer 2023',
        para1: 'Mason Studio is connecting with Interior Designers of Canada and DesignTO at their highly anticipated summer mixer event next Wednesday, July 12 at the Toronto Euro Tile & Stone showroom.',
        // Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset6.jpeg',
        heading: 'Mason Minute with Paul Lee',
        para1: 'Welcome to the Mason Minute - a series celebrating the talented team at Mason Studio. A journal entry and get-to-know moment for the awesome people that contribute to Mason Studio,  ',
        // Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset7.jpeg',
        heading: 'Weaving Collaboration: a community rug',
        para1: '“One can tell by looking at the rug that there are a million different stories written all over it, it’s noisy, and that’s what makes it brilliant," says Mason Studio Project Designer, Nautica Holdip.',
        // Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset8.png',
        heading: 'Creating Engagement: Mason Studio cover feature in May/June 2023 Canadian Interiors Magazine',
        para1: 'Community is an integral element to the method, process and ethos of Mason Studio. We are honoured to be featured on the cover of the May/June 2023 issue of Canadian Interiors Magazine',
        // Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset9.jpeg',
        heading: 'CONTACT 2023 at the Gallery at Mason Studio | Serapis: Firm Like Water',
        para1: 'The Gallery at Mason Studio is thrilled to host Serapis: Firm Like Water , an exhibition part of Scotiabank CONTACT Photography Festival , launching May 12 through June 30. In collaboration with   ',
        // Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },
    {
        imageuurl: '/images/Jasset10.jpeg',
        heading: 'Kadrah Mensah: surely you are joking',
        para1: 'In support of emerging arts practitioners, Mason Studio has proudly partnered with',
        // Location: 'Copenhagen, Denmark ',

        para2: '“I sense a notable transformation in my thinking patterns as I strive to cultivate a distinct vision and streamline my thoughts, by removing unnecessary items and focusing on the core whys and hows." ',
        para3: 'Those are some of many insights Mason Studio Project Designer, Tannaz Torabi, channeled during her first-time visit to Copenhagen, Denmark for Mason Studio’s Work From The World program. The initiative provides Mason Studio team members the opportunity to be sent anywhere they choose in the world to work for a week, returning to bring knowledge and inspiration to all client projects and amongst their colleagues. ',
        para4: 'Tannaz visited Copenhagen in June 2023, where she participated in 3daysofdesign – a festival that provides a platform for both emerging and established design brands from Denmark and abroad to share their talent. Hundreds of exhibitors welcome guests into their spaces to discover new and beloved collections of furniture, lighting, accessories and materials. Events, panel discussions, dining experiences and other adventures abound. ',
        para5: 'While sojourning with international designers and Danes alike, Tannaz was inspired by the local industry’s commitment to quality craftsmanship. ',
        para6: '“Danish designers are gifted in designing furniture, decorative elements that feels timeless and lighting fixtures (both architectural and decorative),” ',
        para7: 'she says.',
        para8: '“Simplicity still feels enough. It is welcoming and draws attention to details. I engaged with spaces, creators and their concepts behind developing their design ideas and their innovative thinking on use of materials, to their inventions around material application.”',
        para9: 'Tannaz is always on-the-go. An avid traveler that has moved frequently over the years, this venture taught her to be a bit more cautious around consumption. It reminded her the importance of keeping things simple, to question the source and sustainability of products, and their societal and environmental impact. ',
        para10: 'Over the course of her total two weeks in CPH, Tannaz grew inspired by the many like-minded peers around her; kind people who are solid listeners that demonstrate an exceptional level of precision in their work. ',
        para11: 'Tannaz had more invigorating moments in Denmark – check out key anecdotes below and stay tuned for the next journal entry for Work From The World!',
        para12: 'Copenhagen made a mark',
        para13: ': to be open-minded, receptive to all diversity, culture, lifestyle, and eager to learn from their experiences.',
        para14: 'Why Tannaz selected Copenhagen for this design venture',
        para15: ': their less-but-better approach in life and consequently in their lifestyle.',
        para16: '  Core research was done through: sites visited, meetings held, people met that had a general idea of all places she would like to see and meet, including individuals from  ',
        para17: 'Tannaz is curious to learn more about',
        para18: ': collaboration between diverse teams, how to support colleagues of diverse background and disciplines.   ',
        para19: 'Innovation was found in',
        para20: ': experiencing spaces that are designed to support users’ well-being.',
        para21: 'Follow Tannaz Torabi ',
        para22: ' @tannaz.torabi '
    },


]